swagger: "2.0"
info:
  version: 1.0.0
  title: whatsmyfit
  description: Whats my fit APIs
basePath: /api/v1
tags:
  - name: Waist
    description: Waist measurement endpoints

consumes:
  - application/json
produces:
  - application/json

definitions:
  WaistBody:
    type: object
    title: waist
    required:
      - value
    properties:
      value:
        type: string
        description: The waist measurement value
      registered:
        type: string
        description: The date this measurement was registered
      type:
        type: string
        description: The type of this measurement
      id:
        type: number
        description: Unique id of this measurement

    example:
      value: "78.0"
      registered: "2018-06-17T23:47:39.278Z"
      type: "WAIST"
      id: 5
paths:
  /waist:
    get:
      tags:
        - Waist
      description: Fetch all waist measurements
      responses:
        200:
          description: Returns all waist measurements
          schema:
            $ref: '#/definitions/WaistBody'
    post:
      tags:
        - Waist
      description: Create a new waist measurement
      parameters:
       - in: body
         name: waist
         description: The waist measurement to register
         schema:
          type: object
          required:
            - value
          properties:
            value:
              type: string
          example:
            value: "75.0"
      responses:
        201:
          description: Returns the new waist measurement
          schema:
            $ref: '#/definitions/WaistBody'

  /waist/{id}:
    get:
      tags:
        - Waist
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the entity to retrieve
          type: integer
      responses:
        200:
          description: Return the waist measurement with the specified id
          schema:
            $ref: '#/definitions/WaistBody'
        404:
          description: No waist measurement found
